//! The desktop shell crate (D-0018 §D1/§D4). The service/model layer is
//! generated by build.rs from src/schema (see build.rs for the pipeline);
//! this file owns the shared AppState and the Tauri run() wiring: SQLite boot
//! in the app data dir, then the generated IPC commands.

pub mod api;
pub mod engine;
pub mod persistence;
pub mod scans;
pub mod schema;
pub mod store;

#[cfg(feature = "daemon")]
pub mod daemon;

use std::sync::Arc;

use sea_orm::DatabaseConnection;
use tauri::Manager;

use crate::engine::{ScanEngine, StubScanEngine};
use crate::schema::AppError;
use crate::store::Store;

/// Application state shared across all handlers (generated IPC/HTTP handlers
/// receive it as `State<Arc<AppState>>`; custom API fns as `&AppState`).
pub struct AppState {
    store: Store,
    engine: Arc<dyn ScanEngine>,
}

impl AppState {
    pub fn new(db: Arc<DatabaseConnection>, engine: Arc<dyn ScanEngine>) -> Self {
        Self {
            store: Store::new(db),
            engine,
        }
    }

    /// Access the store. Generated transport handlers call this.
    pub async fn store(&self) -> Result<&Store, AppError> {
        Ok(&self.store)
    }

    /// The scan-engine seam (stubbed until markdown-contract-engine is wired).
    pub fn engine(&self) -> &dyn ScanEngine {
        self.engine.as_ref()
    }
}

/// SQLite lives in the platform app-data dir Tauri resolves for this app
/// identifier (e.g. ~/.local/share/com.sksizer.markdown-contract on Linux);
/// `mode=rwc` creates the file on first launch, and create_schema is
/// idempotent, so every boot converges.
fn boot_state(app: &tauri::App) -> Result<AppState, Box<dyn std::error::Error>> {
    let data_dir = app.path().app_data_dir()?;
    std::fs::create_dir_all(&data_dir)?;
    let db_path = data_dir.join("markdown-contract.db");
    let url = format!("sqlite://{}?mode=rwc", db_path.display());
    let state = tauri::async_runtime::block_on(async move {
        let db = persistence::db::connect(&url).await?;
        persistence::db::create_schema(&db).await?;
        Ok::<_, sea_orm::DbErr>(AppState::new(Arc::new(db), Arc::new(StubScanEngine)))
    })?;
    Ok(state)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            app.manage(Arc::new(boot_state(app)?));
            Ok(())
        })
        .invoke_handler(api::transport::ipc::ipc_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    /// The IPC smoke test's contract: the Nuxt frontend invokes `echo` and
    /// expects the message back with the "Echo from Rust:" marker (see
    /// app/utils/echo.ts). The command itself now lives in the API layer.
    #[test]
    fn echo_returns_expected_message() {
        let result = crate::api::v1::echo::echo("Hello World");
        assert_eq!(result.unwrap(), "Echo from Rust: Hello World");
    }
}
