//! The desktop shell crate (D-0018 §D1/§D4/§D5). The service/model layer is
//! generated by build.rs from src/schema (see build.rs for the pipeline);
//! this file owns the shared AppState and the Tauri run() wiring: SQLite boot
//! in the app data dir, the generated IPC commands, and the resident-app
//! features — each armed by its own module (watcher, scheduler, tray,
//! notifications), kept thin here.

pub mod api;
pub mod engine;
pub mod notifications;
pub mod openers;
pub mod persistence;
pub mod scans;
pub mod scheduler;
pub mod schema;
pub mod status;
pub mod store;
pub mod tray;
pub mod watcher;

#[cfg(feature = "daemon")]
pub mod daemon;

use std::sync::Arc;

use sea_orm::DatabaseConnection;
use tauri::Manager;
use tokio::sync::broadcast;

use crate::engine::{EngineRouter, ScanEngine};
use crate::scans::ScanCompleted;
use crate::schema::AppError;
use crate::store::Store;

/// Application state shared across all handlers (generated IPC/HTTP handlers
/// receive it as `State<Arc<AppState>>`; custom API fns as `&AppState`).
pub struct AppState {
    store: Store,
    engine: Arc<dyn ScanEngine>,
    /// Scan-completion fan-out: run_scan publishes every finished run here;
    /// notifications (webview event + OS toast) subscribe.
    scan_tx: broadcast::Sender<ScanCompleted>,
}

impl AppState {
    pub fn new(db: Arc<DatabaseConnection>, engine: Arc<dyn ScanEngine>) -> Self {
        let (scan_tx, _) = broadcast::channel(64);
        Self {
            store: Store::new(db),
            engine,
            scan_tx,
        }
    }

    /// Access the store. Generated transport handlers call this.
    pub async fn store(&self) -> Result<&Store, AppError> {
        Ok(&self.store)
    }

    /// The scan-engine seam (production: the [`EngineRouter`] — native
    /// markdown-contract-engine with the TS-CLI fallback).
    pub fn engine(&self) -> &dyn ScanEngine {
        self.engine.as_ref()
    }

    /// The engine as an owned handle — for `spawn_blocking` off the executor
    /// (engine scans are fs/CPU-bound and may block on a child process).
    pub fn engine_arc(&self) -> Arc<dyn ScanEngine> {
        self.engine.clone()
    }

    /// Publish one finished run (called by scans::run_scan). Send errors mean
    /// "no subscribers yet" and are deliberately ignored.
    pub fn notify_scan_completed(&self, msg: ScanCompleted) {
        let _ = self.scan_tx.send(msg);
    }

    /// Subscribe to finished runs (notifications, tray, tests).
    pub fn subscribe_scan_completions(&self) -> broadcast::Receiver<ScanCompleted> {
        self.scan_tx.subscribe()
    }
}

/// SQLite lives in the platform app-data dir Tauri resolves for this app
/// identifier (e.g. ~/.local/share/com.sksizer.markdown-contract on Linux);
/// `mode=rwc` creates the file on first launch, and create_schema is
/// idempotent, so every boot converges.
fn boot_state(app: &tauri::App) -> Result<AppState, Box<dyn std::error::Error>> {
    let data_dir = app.path().app_data_dir()?;
    std::fs::create_dir_all(&data_dir)?;
    let db_path = data_dir.join("markdown-contract.db");
    let url = format!("sqlite://{}?mode=rwc", db_path.display());
    let state = tauri::async_runtime::block_on(async move {
        let db = persistence::db::connect(&url).await?;
        persistence::db::create_schema(&db).await?;
        Ok::<_, sea_orm::DbErr>(AppState::new(
            Arc::new(db),
            Arc::new(EngineRouter::default()),
        ))
    })?;
    Ok(state)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .setup(|app| {
            app.manage(Arc::new(boot_state(app)?));
            let handle = app.handle().clone();

            // The resident-app features (D-0018 §D5), each self-arming and
            // self-rearming off the Store's change broadcast.
            notifications::spawn(handle.clone()); // scan:completed event + OS toasts
            watcher::spawn(handle.clone()); // scan on change
            scheduler::spawn(handle.clone()); // cron scans
            tray::spawn(handle.clone()); // resident tray menu

            // Startup sweep: scan every vault, non-blocking (the daemon's
            // queueMicrotask-revalidate analogue).
            tauri::async_runtime::spawn(async move {
                let state: Arc<AppState> = handle.state::<Arc<AppState>>().inner().clone();
                scans::scan_all(&state, "startup").await;
            });
            Ok(())
        })
        // Resident app: closing the window hides to the tray; the real exit
        // is the tray menu's Quit (tray.rs).
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .invoke_handler(api::transport::ipc::ipc_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod tests {
    /// The IPC smoke test's contract: the Nuxt frontend invokes `echo` and
    /// expects the message back with the "Echo from Rust:" marker (see
    /// app/utils/echo.ts). The command itself now lives in the API layer.
    #[test]
    fn echo_returns_expected_message() {
        let result = crate::api::v1::echo::echo("Hello World");
        assert_eq!(result.unwrap(), "Echo from Rust: Hello World");
    }
}
