// Auto-generated by ontogen. DO NOT EDIT.
// Schema-known surface: entities + generated Create/Update DTOs.

export type Vault = {
  id: string;
  name: string;
  path: string;
  config_path: string;
  watch_enabled: boolean;
  schedule: string | null;
  created_at: string;
  updated_at: string;
};

export type CreateVaultInput = {
  id: string;
  name: string;
  path: string;
  config_path: string;
  watch_enabled: boolean;
  schedule: string | null;
  created_at: string;
  updated_at: string;
};

export type UpdateVaultInput = {
  name?: string | null;
  path?: string | null;
  config_path?: string | null;
  watch_enabled?: boolean | null;
  schedule?: string | null | null;
  created_at?: string | null;
  updated_at?: string | null;
};

export type FindingRecord = {
  id: string;
  scan_run_id: string;
  finding_id: string;
  level: string;
  file_path: string;
  line: number | null;
  col: number | null;
  message: string;
};

export type CreateFindingRecordInput = {
  id: string;
  scan_run_id: string;
  finding_id: string;
  level: string;
  file_path: string;
  line: number | null;
  col: number | null;
  message: string;
};

export type UpdateFindingRecordInput = {
  scan_run_id?: string | null;
  finding_id?: string | null;
  level?: string | null;
  file_path?: string | null;
  line?: number | null | null;
  col?: number | null | null;
  message?: string | null;
};

export type OpenerPreference = {
  id: string;
  app_id: string;
  enabled: boolean;
  sort_order: number;
};

export type CreateOpenerPreferenceInput = {
  id: string;
  app_id: string;
  enabled: boolean;
  sort_order: number;
};

export type UpdateOpenerPreferenceInput = {
  app_id?: string | null;
  enabled?: boolean | null;
  sort_order?: number | null;
};

export type ScanRun = {
  id: string;
  vault_id: string;
  started_at: string;
  finished_at: string | null;
  trigger: string;
  status: string;
  error_count: number;
  warn_count: number;
  report_count: number;
  error_message: string | null;
};

export type CreateScanRunInput = {
  id: string;
  vault_id: string;
  started_at: string;
  finished_at: string | null;
  trigger: string;
  status: string;
  error_count: number;
  warn_count: number;
  report_count: number;
  error_message: string | null;
};

export type UpdateScanRunInput = {
  vault_id?: string | null;
  started_at?: string | null;
  finished_at?: string | null | null;
  trigger?: string | null;
  status?: string | null;
  error_count?: number | null;
  warn_count?: number | null;
  report_count?: number | null;
  error_message?: string | null | null;
};

// Long-tail types (emitted via ontogen-ts AST walker).
export type OpenPreview = {
  program: string;
  args: string[];
};

export type OpenerInfo = {
  app_id: string;
  name: string;
  command: string;
  accepts_directories: boolean;
  accepts_markdown: boolean;
  sort_order: number;
};
