#![allow(dead_code, unused_imports, clippy::pedantic)]
//! Auto-generated Tauri IPC command handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::sync::Arc;

use tauri::State;

use crate::api::v1::{echo, finding_record, opener_preference, openers, scan, scan_run, vault};
use crate::schema::{
    CreateFindingRecordInput, CreateOpenerPreferenceInput, CreateScanRunInput, CreateVaultInput,
    FindingRecord, OpenPreview, OpenerInfo, OpenerPreference, ScanRun, UpdateFindingRecordInput,
    UpdateOpenerPreferenceInput, UpdateScanRunInput, UpdateVaultInput, Vault,
};
use crate::store::Store;
use crate::AppState;

// ── Echo IPC Commands ──

#[tauri::command]
pub async fn echo(message: String) -> Result<String, String> {
    echo::echo(&message).map_err(|e| e.to_string())
}

// ── Finding_record IPC Commands ──

#[tauri::command]
pub async fn finding_record_list(
    state: State<'_, Arc<AppState>>,
) -> Result<Vec<FindingRecord>, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    finding_record::list(&store)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn finding_record_get_by_id(
    id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<FindingRecord, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    finding_record::get_by_id(&store, &id)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn finding_record_create(
    input: CreateFindingRecordInput,
    state: State<'_, Arc<AppState>>,
) -> Result<FindingRecord, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    finding_record::create(&store, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn finding_record_update(
    id: String,
    input: UpdateFindingRecordInput,
    state: State<'_, Arc<AppState>>,
) -> Result<FindingRecord, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    finding_record::update(&store, &id, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn finding_record_delete(
    id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<(), String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    finding_record::delete(&store, &id)
        .await
        .map_err(|e| e.to_string())
}

// ── Opener_preference IPC Commands ──

#[tauri::command]
pub async fn opener_preference_list(
    state: State<'_, Arc<AppState>>,
) -> Result<Vec<OpenerPreference>, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    opener_preference::list(&store)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn opener_preference_get_by_id(
    id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<OpenerPreference, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    opener_preference::get_by_id(&store, &id)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn opener_preference_create(
    input: CreateOpenerPreferenceInput,
    state: State<'_, Arc<AppState>>,
) -> Result<OpenerPreference, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    opener_preference::create(&store, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn opener_preference_update(
    id: String,
    input: UpdateOpenerPreferenceInput,
    state: State<'_, Arc<AppState>>,
) -> Result<OpenerPreference, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    opener_preference::update(&store, &id, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn opener_preference_delete(
    id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<(), String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    opener_preference::delete(&store, &id)
        .await
        .map_err(|e| e.to_string())
}

// ── Scan_run IPC Commands ──

#[tauri::command]
pub async fn scan_run_list(state: State<'_, Arc<AppState>>) -> Result<Vec<ScanRun>, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    scan_run::list(&store).await.map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn scan_run_get_by_id(
    id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<ScanRun, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    scan_run::get_by_id(&store, &id)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn scan_run_create(
    input: CreateScanRunInput,
    state: State<'_, Arc<AppState>>,
) -> Result<ScanRun, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    scan_run::create(&store, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn scan_run_update(
    id: String,
    input: UpdateScanRunInput,
    state: State<'_, Arc<AppState>>,
) -> Result<ScanRun, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    scan_run::update(&store, &id, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn scan_run_delete(id: String, state: State<'_, Arc<AppState>>) -> Result<(), String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    scan_run::delete(&store, &id)
        .await
        .map_err(|e| e.to_string())
}

// ── Vault IPC Commands ──

#[tauri::command]
pub async fn vault_list(state: State<'_, Arc<AppState>>) -> Result<Vec<Vault>, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    vault::list(&store).await.map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn vault_get_by_id(id: String, state: State<'_, Arc<AppState>>) -> Result<Vault, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    vault::get_by_id(&store, &id)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn vault_create(
    input: CreateVaultInput,
    state: State<'_, Arc<AppState>>,
) -> Result<Vault, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    vault::create(&store, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn vault_update(
    id: String,
    input: UpdateVaultInput,
    state: State<'_, Arc<AppState>>,
) -> Result<Vault, String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    vault::update(&store, &id, input)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn vault_delete(id: String, state: State<'_, Arc<AppState>>) -> Result<(), String> {
    let store = state.store().await.map_err(|e| e.to_string())?;
    vault::delete(&store, &id).await.map_err(|e| e.to_string())
}

// ── Openers IPC Commands ──

#[tauri::command]
pub async fn list_openers(state: State<'_, Arc<AppState>>) -> Result<Vec<OpenerInfo>, String> {
    openers::list_openers(&state)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn open_path(
    path: String,
    app_id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<(), String> {
    openers::open_path(&state, path, app_id)
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn preview_open(
    path: String,
    app_id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<OpenPreview, String> {
    openers::preview_open(&state, path, app_id)
        .await
        .map_err(|e| e.to_string())
}

// ── Scan IPC Commands ──

#[tauri::command]
pub async fn scan_now(
    vault_id: String,
    state: State<'_, Arc<AppState>>,
) -> Result<ScanRun, String> {
    scan::scan_now(&state, vault_id)
        .await
        .map_err(|e| e.to_string())
}

/// Generated IPC handler. Wire this into `tauri::Builder::invoke_handler()`.
pub fn ipc_handler() -> impl Fn(tauri::ipc::Invoke) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        echo,
        finding_record_list,
        finding_record_get_by_id,
        finding_record_create,
        finding_record_update,
        finding_record_delete,
        opener_preference_list,
        opener_preference_get_by_id,
        opener_preference_create,
        opener_preference_update,
        opener_preference_delete,
        scan_run_list,
        scan_run_get_by_id,
        scan_run_create,
        scan_run_update,
        scan_run_delete,
        vault_list,
        vault_get_by_id,
        vault_create,
        vault_update,
        vault_delete,
        list_openers,
        open_path,
        preview_open,
        scan_now,
    ]
}
