//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new FindingRecord.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateFindingRecordInput {
    #[serde(default)]
    pub id: String,
    pub scan_run_id: String,
    pub finding_id: String,
    pub level: String,
    pub file_path: String,
    #[serde(default)]
    pub line: Option<i32>,
    #[serde(default)]
    pub col: Option<i32>,
    pub message: String,
}

/// Input for updating an existing FindingRecord.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateFindingRecordInput {
    #[serde(default)]
    pub scan_run_id: Option<String>,
    #[serde(default)]
    pub finding_id: Option<String>,
    #[serde(default)]
    pub level: Option<String>,
    #[serde(default)]
    pub file_path: Option<String>,
    #[serde(default)]
    pub line: Option<Option<i32>>,
    #[serde(default)]
    pub col: Option<Option<i32>>,
    #[serde(default)]
    pub message: Option<String>,
}
