//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new OpenerPreference.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateOpenerPreferenceInput {
    #[serde(default)]
    pub id: String,
    pub app_id: String,
    pub enabled: bool,
    pub sort_order: i32,
}

/// Input for updating an existing OpenerPreference.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateOpenerPreferenceInput {
    #[serde(default)]
    pub app_id: Option<String>,
    #[serde(default)]
    pub enabled: Option<bool>,
    #[serde(default)]
    pub sort_order: Option<i32>,
}
