//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new ScanRun.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateScanRunInput {
    pub id: String,
    pub vault_id: String,
    pub started_at: String,
    #[serde(default)]
    pub finished_at: Option<String>,
    pub trigger: String,
    pub status: String,
    pub error_count: i32,
    pub warn_count: i32,
    pub report_count: i32,
    #[serde(default)]
    pub error_message: Option<String>,
}

/// Input for updating an existing ScanRun.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateScanRunInput {
    #[serde(default)]
    pub vault_id: Option<String>,
    #[serde(default)]
    pub started_at: Option<String>,
    #[serde(default)]
    pub finished_at: Option<Option<String>>,
    #[serde(default)]
    pub trigger: Option<String>,
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub error_count: Option<i32>,
    #[serde(default)]
    pub warn_count: Option<i32>,
    #[serde(default)]
    pub report_count: Option<i32>,
    #[serde(default)]
    pub error_message: Option<Option<String>>,
}
