//! Generated by ontogen. DO NOT EDIT.

use schemars::JsonSchema;
use serde::Deserialize;

/// Input for creating a new Vault.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct CreateVaultInput {
    pub id: String,
    pub name: String,
    pub path: String,
    pub config_path: String,
    pub watch_enabled: bool,
    #[serde(default)]
    pub schedule: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

/// Input for updating an existing Vault.
/// All fields are optional; only provided fields are updated.
#[derive(Debug, Clone, Deserialize, JsonSchema, specta::Type)]
pub struct UpdateVaultInput {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub path: Option<String>,
    #[serde(default)]
    pub config_path: Option<String>,
    #[serde(default)]
    pub watch_enabled: Option<bool>,
    #[serde(default)]
    pub schedule: Option<Option<String>>,
    #[serde(default)]
    pub created_at: Option<String>,
    #[serde(default)]
    pub updated_at: Option<String>,
}
