#![allow(dead_code, unused_imports, clippy::pedantic)]
//! Auto-generated HTTP route handlers. DO NOT EDIT.
//!
//! Generated by ontogen from API source files.

use std::sync::Arc;

use axum::{
    extract::{Path, Query, State},
    http::StatusCode,
    response::Json,
    routing::{delete, get, post, put},
    Router,
};

use serde::{Deserialize, Serialize};

use crate::api::v1::{echo, finding_record, opener_preference, openers, scan, scan_run, vault};
use crate::schema::{
    CreateFindingRecordInput, CreateOpenerPreferenceInput, CreateScanRunInput, CreateVaultInput,
    FindingRecord, OpenPreview, OpenerInfo, OpenerPreference, ScanRun, UpdateFindingRecordInput,
    UpdateOpenerPreferenceInput, UpdateScanRunInput, UpdateVaultInput, Vault,
};
use crate::store::Store;
use crate::AppState;

#[derive(Serialize)]
struct ErrorResponse {
    error: String,
}

type ApiError = (StatusCode, Json<ErrorResponse>);

fn err(msg: String) -> ApiError {
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        Json(ErrorResponse { error: msg }),
    )
}

// ── Echo Handlers ──

#[derive(Deserialize)]
struct EchoEchoBody {
    message: String,
}

async fn echo(Json(body): Json<EchoEchoBody>) -> Result<Json<String>, ApiError> {
    echo::echo(&body.message)
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

// ── Finding_record Handlers ──

async fn finding_record_list(
    State(state): State<Arc<AppState>>,
) -> Result<Json<Vec<FindingRecord>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    finding_record::list(&store)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn finding_record_get_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<Json<FindingRecord>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    finding_record::get_by_id(&store, &id)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn finding_record_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateFindingRecordInput>,
) -> Result<(StatusCode, Json<FindingRecord>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    finding_record::create(&store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.to_string()))
}

async fn finding_record_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateFindingRecordInput>,
) -> Result<Json<FindingRecord>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    finding_record::update(&store, &id, input)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn finding_record_delete(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    finding_record::delete(&store, &id)
        .await
        .map(|_| StatusCode::NO_CONTENT)
        .map_err(|e| err(e.to_string()))
}

// ── Opener_preference Handlers ──

async fn opener_preference_list(
    State(state): State<Arc<AppState>>,
) -> Result<Json<Vec<OpenerPreference>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    opener_preference::list(&store)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn opener_preference_get_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<Json<OpenerPreference>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    opener_preference::get_by_id(&store, &id)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn opener_preference_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateOpenerPreferenceInput>,
) -> Result<(StatusCode, Json<OpenerPreference>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    opener_preference::create(&store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.to_string()))
}

async fn opener_preference_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateOpenerPreferenceInput>,
) -> Result<Json<OpenerPreference>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    opener_preference::update(&store, &id, input)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn opener_preference_delete(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    opener_preference::delete(&store, &id)
        .await
        .map(|_| StatusCode::NO_CONTENT)
        .map_err(|e| err(e.to_string()))
}

// ── Scan_run Handlers ──

async fn scan_run_list(State(state): State<Arc<AppState>>) -> Result<Json<Vec<ScanRun>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    scan_run::list(&store)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn scan_run_get_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<Json<ScanRun>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    scan_run::get_by_id(&store, &id)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn scan_run_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateScanRunInput>,
) -> Result<(StatusCode, Json<ScanRun>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    scan_run::create(&store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.to_string()))
}

async fn scan_run_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateScanRunInput>,
) -> Result<Json<ScanRun>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    scan_run::update(&store, &id, input)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn scan_run_delete(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    scan_run::delete(&store, &id)
        .await
        .map(|_| StatusCode::NO_CONTENT)
        .map_err(|e| err(e.to_string()))
}

// ── Vault Handlers ──

async fn vault_list(State(state): State<Arc<AppState>>) -> Result<Json<Vec<Vault>>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    vault::list(&store)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn vault_get_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<Json<Vault>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    vault::get_by_id(&store, &id)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn vault_create(
    State(state): State<Arc<AppState>>,
    Json(input): Json<CreateVaultInput>,
) -> Result<(StatusCode, Json<Vault>), ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    vault::create(&store, input)
        .await
        .map(|entity| (StatusCode::CREATED, Json(entity)))
        .map_err(|e| err(e.to_string()))
}

async fn vault_update(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
    Json(input): Json<UpdateVaultInput>,
) -> Result<Json<Vault>, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    vault::update(&store, &id, input)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

async fn vault_delete(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {
    let store = state.store().await.map_err(|e| err(e.to_string()))?;
    vault::delete(&store, &id)
        .await
        .map(|_| StatusCode::NO_CONTENT)
        .map_err(|e| err(e.to_string()))
}

// ── Openers Handlers ──

async fn list_openers(
    State(state): State<Arc<AppState>>,
) -> Result<Json<Vec<OpenerInfo>>, ApiError> {
    openers::list_openers(&state)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

#[derive(Deserialize)]
struct OpenersOpenPathBody {
    path: String,
    app_id: String,
}

async fn open_path(
    State(state): State<Arc<AppState>>,
    Json(body): Json<OpenersOpenPathBody>,
) -> Result<StatusCode, ApiError> {
    openers::open_path(&state, body.path, body.app_id)
        .await
        .map(|_| StatusCode::NO_CONTENT)
        .map_err(|e| err(e.to_string()))
}

#[derive(Deserialize)]
struct OpenersPreviewOpenBody {
    path: String,
    app_id: String,
}

async fn preview_open(
    State(state): State<Arc<AppState>>,
    Json(body): Json<OpenersPreviewOpenBody>,
) -> Result<Json<OpenPreview>, ApiError> {
    openers::preview_open(&state, body.path, body.app_id)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

// ── Scan Handlers ──

#[derive(Deserialize)]
struct ScanScanNowBody {
    vault_id: String,
}

async fn scan_now(
    State(state): State<Arc<AppState>>,
    Json(body): Json<ScanScanNowBody>,
) -> Result<Json<ScanRun>, ApiError> {
    scan::scan_now(&state, body.vault_id)
        .await
        .map(Json)
        .map_err(|e| err(e.to_string()))
}

/// Generated routes. Call this from your main router.
pub fn entity_routes() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/echos", post(echo))
        .route(
            "/api/finding-records",
            get(finding_record_list).post(finding_record_create),
        )
        .route(
            "/api/finding-records/:id",
            get(finding_record_get_by_id)
                .put(finding_record_update)
                .delete(finding_record_delete),
        )
        .route(
            "/api/opener-preferences",
            get(opener_preference_list).post(opener_preference_create),
        )
        .route(
            "/api/opener-preferences/:id",
            get(opener_preference_get_by_id)
                .put(opener_preference_update)
                .delete(opener_preference_delete),
        )
        .route("/api/scan-runs", get(scan_run_list).post(scan_run_create))
        .route(
            "/api/scan-runs/:id",
            get(scan_run_get_by_id)
                .put(scan_run_update)
                .delete(scan_run_delete),
        )
        .route("/api/vaults", get(vault_list).post(vault_create))
        .route(
            "/api/vaults/:id",
            get(vault_get_by_id).put(vault_update).delete(vault_delete),
        )
        .route("/api/openers/list", get(list_openers))
        .route("/api/openers/open-path", post(open_path))
        .route("/api/openers/preview-open", post(preview_open))
        .route("/api/scans/now", post(scan_now))
}
